### ISSUE TITLE
[チケットページ] チケット名のカラーの変更

### ISSUE THREAD

**Issue by shusei-t** [wctokyo/2023-wctokyo-styles#122]
# 問題点
新デザインでは、チケットページにてチケット名が見えない状態です。
添付スクリーンショット参照。
![Screenshot 2023-09-15 at 22 41 08](https://github.com/wctokyo/2023-wctokyo-styles/assets/53067918/7a4d462b-e002-4ca3-b493-26aa2a2b0f40)

# 改善要望
チケット名が見えるように #000000 のような色指定にしてもらえると良いと思います。

ありがとうございます。

**Comment by lunaluna** [comment]
@shusei-t 
修正しましたのでご確認ください！

![screenshot_2023-09-15_22 55 39](https://github.com/wctokyo/2023-wctokyo-styles/assets/1078657/5c0b4c88-55ad-4747-9cf1-7261390ccf1c)

https://tokyo.wordcamp.org/2023/tickets/

**Comment by shusei-t** [comment]
@lunaluna 
とても見やすくなった気がします！
対応ありがとうございます。
