### ISSUE TITLE
コンテンツエリアにword-breakを入れてほしい

### ISSUE THREAD

**Issue by hidekazu-matsubara** [wctokyo/2023-wctokyo-styles#124]
URLを入れた時に折り返しされるように。

**Comment by shusei-t** [comment]
# 該当ページ
https://tokyo.wordcamp.org/2023/sponsors-only/

**Comment by lunaluna** [comment]
@hidekazu-matsubara さん @shusei-t さん

URL を直接記載していたところをテキストリンクに置き換えました。
これでご確認ください！

**Comment by shusei-t** [comment]
Looks good! Let's close the issue!
