### ISSUE TITLE
【Bug】600px でナビゲーションのスタイルが崩れる

### ISSUE THREAD

**Issue by lunaluna** [wctokyo/2023-wctokyo-styles#137]

**Comment by miiiko** [comment]
src/scss/_variables.scss

$breakpointsの設定で、`'pc': 'screen and (max-width: 600px)', `となっていたのを`'pc': 'screen and (max-width: 599px)', `へ修正済み。
修正履歴URL
https://github.com/wctokyo/2023-wctokyo-styles/commit/4663a57cd0f1fc1afcf12e05633cd70c64b3b01b#diff-e5a2bc9e76b60200872fec420e32a890b2035706e458f23e9b901b4faad9ee6c

**Comment by lunaluna** [comment]
修正内容が確認できたのでクローズ
