### ISSUE TITLE
トップページのスポンサーエリアのスポンサーロゴの表示サイズ変更について

### ISSUE THREAD

**Issue by lunaluna** [wctokyo/2023-wctokyo-styles#164]
* ランチスポンサー： シルバーのサイズ
* アフターパーティ： ゴールドのサイズ
* インカインド： シルバーのサイズ

に修正をお願いします。
可能であればちょっと急いで修正したいですm(_ _)m

**Comment by lunaluna** [comment]
@miiiko さん
ごめんなさい、ランチスポンサーはそのままでOKです。

* アフターパーティ： ゴールドのサイズ
* インカインド： シルバーのサイズ

こちらだけ対応をお願いしますm(_ _)m

**Comment by miiiko** [comment]
@lunaluna 
了解いたしました！
対応いたしましたのでクローズします
