### ISSUE TITLE
【開催概要】スマホ表示のときに「日程・場所」のスタイルがトップページと異なる

### ISSUE THREAD

**Issue by lunaluna** [wctokyo/2023-wctokyo-styles#57]
URL： https://tokyo.wordcamp.org/2023/outline/

スクショ：
![screenshot_2023-06-21_14 45 52](https://github.com/wctokyo/2023-wctokyo-styles/assets/1078657/c81c4eee-21ad-40a4-b69a-7016279e657c)

**Comment by miiiko** [comment]
対応済み。
追加CSSクラスに　`teaser-home--abstruct--place`　追加
