### ISSUE TITLE
【お問い合わせ】PC 表示のときにフォームがページ左右中央になるようにしたい

### ISSUE THREAD

**Issue by lunaluna** [wctokyo/2023-wctokyo-styles#58]
URL： https://tokyo.wordcamp.org/2023/contact/

スクショ：
![screenshot_2023-06-21_17 54 02](https://github.com/wctokyo/2023-wctokyo-styles/assets/1078657/cffe5df8-c381-4c13-9cf0-58289bd580c7)

**Comment by lunaluna** [comment]
※ 可能なら
スマホのときにフォームが画面幅に収まるようにしたい…

スクショ：
![screenshot_2023-06-21_18 35 59](https://github.com/wctokyo/2023-wctokyo-styles/assets/1078657/24d24ec9-42f9-4c02-a3cd-921139d7c25c)

**Comment by bissy** [comment]
@lunaluna フォームは以下の観点から、埋め込みより外部で開いた方がいい気がします！
- 操作性
- 可読性
- メンテナンス性

**Comment by lunaluna** [comment]
@bissy さん

お問い合わせについては「ページ」は作成せずにフォームへのリンクだけの方がいい？
なにかしらの表示の条件（WordCamp のサイトにはお問い合わせページが存在しなくてはいけない、とか）がないか確認しますー。

**Comment by lunaluna** [comment]
@bissy さん

確認したところ、必ずしもお問い合わせの「ページ」が存在する必要はない、とのことでした。
なのでページ「お問い合わせ」は非表示にして、当該ページへのリンクは Google フォームへの直リンクとしてください。

リンク： https://forms.gle/1sYpEGTr6gh1F1Td8

**Comment by miiiko** [comment]
ヘッダとフッタのお問合せはgoogleフォームへの直リンクになっていたので、固定ページのお問合せを非公開へ変更
