### ISSUE TITLE
【お知らせ】いろいろ修正したい

### ISSUE THREAD

**Issue by lunaluna** [wctokyo/2023-wctokyo-styles#59]
URL： https://tokyo.wordcamp.org/2023/news/

修正したい詳細：

- [ ] （たぶん）テンプレートが正しく設定されていないので、その調査と修正
     - [ ] テンプレートは「ホーム」を利用し、表示設定で「投稿ページ」にしているが、アイキャッチ画像が正しく反映されていない
- [ ] そもそも「news」ページならカテゴリー：お知らせ（announcements）を表示するのがいいのでは？
     - [ ] 現状は投稿全て（カテゴリー：お知らせ、ブログ）が表示される
     - [ ] お知らせ一覧（ https://tokyo.wordcamp.org/2023/category/announcements/ ）は別途存在する
- [x] スタイルの調整
     - [x] 記事タイトル文字サイズなど
     - [x] 全体の余白感など調整
- [x] 投稿日の表示

スクショ：
![screenshot_2023-06-21_18 14 13](https://github.com/wctokyo/2023-wctokyo-styles/assets/1078657/e07dc627-b46e-4298-9b7e-4b640dd94a10)

**Comment by lunaluna** [comment]
【一部アップデート】

カテゴリー `announcement` はカテゴリー `news` に上書き済み
（それ以外の条件は現状変わっていない）

**Comment by miiiko** [comment]
@lunaluna 
>（たぶん）テンプレートが正しく設定されていないので、その調査と修正

ここはちょっと相談したいです

> そもそも「news」ページならカテゴリー：お知らせ（announcements）を表示するのがいいのでは？

現状投稿全てが「お知らせ」で投稿されているようです
また、カテゴリの`announcements`は`news`にスラッグ変更済

**Comment by miiiko** [comment]
> テンプレートは「ホーム」を利用し、表示設定で「投稿ページ」にしているが、アイキャッチ画像が正しく反映されていない

https://asia.wordcamp.org/2023/news/
https://tokyo.wordcamp.org/2019/news/
https://us.wordcamp.org/2023/news/

上記らへんも同じ症状がでている模様なので対処不可能の可能性が高い
