### ISSUE TITLE
【全体】Theme.json・CSS変数・カスタムスタイルが使えない（システムをブロックエディタへ対応したい）

### ISSUE THREAD

**Issue by bissy** [wctokyo/2023-wctokyo-styles#61]
今、CSS変数が、style.cssでもカスタマイザーでも上書き不可能になっていて、頭を悩ませています。
あとブロックエディタのスタイルパネルなどが、Theme.jsonが使えないために、デザインに合わせた仕様にできておらず、運用の面で不安があります。
欲を言えばカスタムスタイルも使えるようにもしたいです（プラグイン経由で指定は可能なものの、現状phpが扱えないので未対応）。

**Comment by lunaluna** [comment]
https://github.com/WordPress/wordcamp.org

これについては ↑ こっちに issue 立てる案件なのではないかなぁと思います。現状ではブロックテーマの theme.json を外部から読み込んで上書きできる機能がないので、WordCamp のサイト全体でその機能が実装されないと使えない、という認識ですね…。

WordCamp のサイトはそもそも自由度がめちゃくちゃ低い中で運用しなくてはならず、以前から css ファイルひとつしか読み込ませられなかったという経緯があります。
今後ブロックテーマが主流になっていく中で当然こういった要望は色々なところから出てくるはずなので、現時点では ↑ のリポジトリに issue を立てて「こういうことができるようになると嬉しい」と伝えるのが最善かなぁ、と思っています。

ちょっと検索したところ、 WordCamp のリポジトリで theme.json に言及されている issue は

https://github.com/WordPress/wordcamp.org/issues/622

だけで、最終的に「Gutenberg プロジェクトに任せましょう」みたいになっちゃってるので、少なくともいまの時点で対応するのは難しいと思います。

**Comment by miminari** [comment]
@bissy cc @lunaluna 
こんにちは！今年のTokyoには間に合わない気はしますが、これからのWordCampについてはココで議論する？気がするので良かったらチェックしてみてください。（そして、できたら思いの丈を書いてもらえたら嬉しいです。）
https://github.com/WordPress/wordcamp.org/issues/870

**Comment by lunaluna** [comment]
@miminari さん

コメントありがとうございます！！こちら確認します！
