### ISSUE TITLE
【本サイト】投稿ページのCSS準備

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#66]
- [x] ヘッダ画像
- [x] h1
- [x] h2
- [x] h3
- [x] h4
- [x] p
- [x] マーカー
- [x] 画像
- [x] ul
- [x] ol
- [x] テキストリンク / hover
- [x] ボタン / hover
- [x] table
- [x] 引用

---
以下は後回し

- [ ] メディアと文章（2カラム）
- [ ] メディア（2カラム）
- [ ] 目次

**Comment by lunaluna** [comment]
@miiiko さん

こちらの未着手分については多分もう使わないのでww、これで完了にします！！！
ありがとうございましたー
