### ISSUE TITLE
【本サイト】スポンサーページ作成

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#69]
デザイン不要の想定です。
TOPページのデザインを踏襲する形で実装を行う

CSSは2019を参考に
https://tokyo.wordcamp.org/2019/sponsors/

**Comment by miiiko** [comment]
関連デザイン : #91

**Comment by lunaluna** [comment]
https://tokyo.wordcamp.org/2023/sponsors/
https://tokyo.wordcamp.org/2023/sponsor/wordpress-dot-com/

あるので OK
