### ISSUE TITLE
【本サイト】よくある質問

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#70]
基本的には投稿ページを踏襲
独自の箇所はデザインを参考

https://www.figma.com/file/4rDzZUmFEDhLCDtUfDHxE0/WordCamp-Tokyo-2023?type=design&node-id=935%3A360&mode=design&t=BprNWKV79q3oveMp-1

メインサイトカンプ > FAQ

**Comment by lunaluna** [comment]
https://github.com/wctokyo/2023-wctokyo-styles/issues/93
#93 

と重複する課題のためクローズ
