### ISSUE TITLE
【本サイト】TOPページ / ショートカットアイコンリンクエリア

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#88]
<img width="584" alt="スクリーンショット 2023-08-23 1 39 47" src="https://github.com/wctokyo/2023-wctokyo-styles/assets/10355772/4f73b04f-9483-4546-9fc3-d1154a0c34e9">

**Comment by lunaluna** [comment]
@miiiko さん

チケットが完売しそうなので、ここに「チケット」のショートカットは不要かも。
変わりに「フロアマップ」のショートカットが入れられるといいかなと思いますがどうでしょう？

アイコンのデザインを作るかデザインチームの誰かに依頼できそうでしょうか？

**Comment by miiiko** [comment]
@lunaluna 

その方が良さそうですね！
アイコン作成依頼してきます〜！
