### ISSUE TITLE
【本サイト】TOPページ / 新着一覧エリア

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#89]
<img width="604" alt="スクリーンショット 2023-08-23 1 40 42" src="https://github.com/wctokyo/2023-wctokyo-styles/assets/10355772/d415d75d-9e81-44b0-be6d-0159803a75c8">

**Comment by lunaluna** [comment]
対応する際に、カテゴリー部分のカテゴリー一覧ページへのリンクはキャンセルしておいてください。
