### ISSUE TITLE
【本サイト】TOPページ / カウントダウンエリア

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#92]
<img width="491" alt="スクリーンショット 2023-08-23 1 42 24" src="https://github.com/wctokyo/2023-wctokyo-styles/assets/10355772/09921c80-7d2d-4cbf-a041-01140296d5e0">

**Comment by lunaluna** [comment]
【カウントダウンエリアについて】
最新の状態だとうまく動作しないとの情報あり

もしうまく動かない場合は対応しない（表示しない）

**Comment by lunaluna** [comment]
対応しない
