### ISSUE TITLE
【本サイト】FAQページ

### ISSUE THREAD

**Issue by miiiko** [wctokyo/2023-wctokyo-styles#93]
ベース #66 
QとA箇所のみ新規スタイル

**Comment by lunaluna** [comment]
基本的には投稿ページを踏襲
独自の箇所はデザインを参考

https://www.figma.com/file/4rDzZUmFEDhLCDtUfDHxE0/WordCamp-Tokyo-2023?type=design&node-id=935%3A360&mode=design&t=BprNWKV79q3oveMp-1

メインサイトカンプ > FAQ

**Comment by bissy** [comment]
クラスを固定ページに割り当て作業中です

**Comment by lunaluna** [comment]
https://tokyo.wordcamp.org/2023/faq/
